version: "3.9"

services:
  #PostgreSQL Database
  db:
    image: postgres:16
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  #Backend Service
  backend:
    build: ./backend
    container_name: ecommerce_backend
    restart: always
    depends_on:
      - db
    environment:
      PORT: 5000
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
      PGDATABASE: ecommerce
      PGPORT: 5432
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]

  #Frontend Service
  frontend:
    build: ./frontend
    container_name: ecommerce_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000

volumes:
  pgdata:
